site_name: Slim Framework
pages:
    - [index.md, Home]
    - [start/installation.md, Get Started, Installation]
    - [start/web-servers.md, Get Started, Web Servers]
    - [concepts/objects.md, Concepts, Objects]
    - [concepts/di.md, Concepts, Dependency Injection]
    - [concepts/middleware.md, Concepts, Middleware]
    - [concepts/value-objects.md, Concepts, PSR-7]
    - [objects/request.md, Objects, Request]
    - [objects/response.md, Objects, Response]
    - [objects/router.md, Objects, Router]
    - [objects/environment.md, Objects, Environment]
    - [features/templates.html, Features, Views and Templates]
    - [caching.md, Caching]
    - [handlers/error.md, Error Handling, 500 Server Error]
    - [handlers/not-found.md, Error Handling, 404 Not Found]
    - [handlers/not-allowed.md, Error Handling, 405 Not Allowed]
    - [contributors/strategy.md, Contributors, Branching Strategy]
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
